name: "Coverage"

on: [ push, pull_request ]
jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}/src
    steps:
      - uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@v9.0.0
        with:
          python-version: 3.14
      - name: Install dependencies
        run: uv sync --group coverage
      - name: Log into registry
        # GHCR_PAT is a personal access token for the Github Container Registry; You can create it using the following steps:
        # 1) Go to https://github.com/settings/tokens
        # 2) Create a new token (classic as of 2025-02-02)
        # 3) Select the following scopes: read:packages
        # GHCR_USR is the username for the Github Container Registry; it has to match the PAT and is the username of the Github account that created the PAT
        # You can update the tokens in the repository settings:
        # https://github.com/Hochfrequenz/TransformerBeeClient.py/settings/secrets/actions/GHCR_PAT
        # https://github.com/Hochfrequenz/TransformerBeeClient.py/settings/secrets/actions/GHCR_USR
        # Tokens will expire 2025-02-01
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ secrets.GHCR_USR }} --password-stdin
      - name: Run Tests and Record Coverage
        env: # this is for the tests with real oauth-checks
          AUTH0_TEST_CLIENT_ID: ${{ secrets.AUTH0_TEST_CLIENT_ID }}
          AUTH0_TEST_CLIENT_SECRET: ${{ secrets.AUTH0_TEST_CLIENT_SECRET }}
        # note, that we collect the coverage from the integration test path here!
        run: |
          cd integrationtests
          uv run coverage run -m pytest
          uv run coverage html --omit integrationtests/*
          uv run coverage report --fail-under 84 --omit integrationtests/*
